### ISSUE TITLE
Does this mean I can only activate freeze when using native-stack other than stack?

### ISSUE THREAD

**Issue by chj-damon** [software-mansion-labs/react-freeze#10]
I read the document of react-navigation, and noticed that `@react-navigation/native-stack` relies on `react-native-screens`.
if I just use `@react-navigation/stack`, it is still ok that I can use this freeze feature in my app?

**Comment by kacperkapusciak** [comment]
@chj-damon 
These are the 4 navigators that depend on `react-native-screens`:

- `@react-navigation/native-stack`
- `@react-navigation/stack`
- `@react-navigation/drawer`
- `@react-navigation/bottom-tabs`

You can use the freezing feature with each of these!
